Adds support for default Namespace in C#
microsoftgraph/microsoft-graph-explorer-api pull request #322
Opened 2020-09-28 09:42 UTC by andrueastman

2020-09-28 18:34 UTC, ddyett commented
can you just link this one to an issue or create one for tracking purposes?

2020-09-28 18:37 UTC, ddyett commented
var set = new Microsoft.Graph.TermStore.Set
{
	Description = "mySet"
};

there's a part of me that says only add namespaces for non default namespace.  what are your thoughts?

2020-09-28 18:38 UTC, ddyett commented on CodeSnippetsReflection/TypeProperties/CSharpTypeProperties.cs
> +                // Otherwise modify the classname by concatenation the Namespace prefix.
```suggestion
                // Otherwise modify the classname by concatenating with the Namespace prefix.
```

2020-09-28 18:40 UTC, ddyett commented on CodeSnippetsReflection/TypeProperties/CSharpTypeProperties.cs
> +                    fullClassName = fullClassName + "." + uppercaseSegment;
consider changing to stringbuilder for better garbage collection.

2020-09-28 18:43 UTC, ddyett commented on CodeSnippetsReflection/TypeProperties/CSharpTypeProperties.cs
> +                if (namespaceString.Equals(DefaultNamespace) || namespaceString == "Edm")
shouldn't this check have prevented going to the concatenation code?

2020-09-28 18:48 UTC, zengin commented
@andrueastman please add the full diff of the snippet generation using the new code (similar to here https://github.com/microsoftgraph/microsoft-graph-explorer-api/pull/269). The test you added makes sure that the happy path works, but having a full diff would give us confidence in terms of not having any regressions.

2020-09-28 18:51 UTC, zengin requested changes
Can we have `TermStore.Set` instead of `Microsoft.Graph.TermStore.Set` since it is assumed that there is a `using Microsoft.Graph` in the contexts which these snippets appear?

2020-09-29 07:52 UTC, andrueastman commented on CodeSnippetsReflection/TypeProperties/CSharpTypeProperties.cs
> +                if (namespaceString.Equals(DefaultNamespace) || namespaceString == "Edm")
The code returns the default classname if its in the default namesapace.
Otherwise it builds the full type name including the name space.

2020-09-29 08:10 UTC, andrueastman commented
@zengin 
If is use `Termstore.Set` compilation fails. I will reach out to you to get more clarification on this front.

2020-09-29 08:26 UTC, zengin commented
@andrueastman I thought about partial namespace references in C++ when I wrote that comment. It seems like C# doesn't support it without explicit aliasing.

I will sign-off if you have no regression on the full generation.

2020-09-29 09:12 UTC, andrueastman commented
[Snippets Diff ](https://github.com/microsoftgraph/microsoft-graph-docs/commit/cc12eadd210b7b6bf6989a736c9950be3669ee63)

2020-09-29 16:34 UTC, ddyett commented on CodeSnippetsReflection/TypeProperties/CSharpTypeProperties.cs
> +                if (namespaceString.Equals(DefaultNamespace) || namespaceString == "Edm")
my implication here is that since the defaultnamespace is microsoft.graph and termstore is in microsoft.graph shouldn't I just get termstore instead of microsoft.graph.termstore?

2020-09-29 16:39 UTC, ddyett commented on CodeSnippetsReflection/TypeProperties/CSharpTypeProperties.cs
> +                if (namespaceString.Equals(DefaultNamespace) || namespaceString == "Edm")
my confusion is i didn't realize there was a new namespace for termstore.

2020-09-29 16:43 UTC, ddyett approved these changes

2020-09-29 17:26 UTC, zengin approved these changes
Thanks for the diff.

2020-09-30 09:33 UTC, merged