Multiple namespace in objective c snippets
microsoftgraph/microsoft-graph-explorer-api pull request #328
Opened 2020-10-05 09:27 UTC by andrueastman

Closes #324

2020-10-05 15:44 UTC, zengin requested changes

2020-10-05 15:44 UTC, zengin commented on CodeSnippetsReflection/LanguageGenerators/ObjectiveCGenerator.cs
> +            var namespaceModel = (namespaceString.Equals("microsoft.graph") || namespaceString.Equals("Edm")) ? string.Empty : namespaceString.Split(".").Last();
This doesn't address multiple levels of subnamespaces.

Even though we don't have real examples (yet), it is allowed to have multiple subnamespaces. So microsoft.graph.sub1.sub2.type is expected to be converted into MSGraphSub1Sub2Type.

2020-10-05 15:48 UTC, andrueastman commented on CodeSnippetsReflection/LanguageGenerators/ObjectiveCGenerator.cs
> +            var namespaceModel = (namespaceString.Equals("microsoft.graph") || namespaceString.Equals("Edm")) ? string.Empty : namespaceString.Split(".").Last();
Agreed. I will action and resolve.

2020-10-05 16:42 UTC, andrueastman commented
@zengin I have verified that the [update](https://github.com/microsoftgraph/microsoft-graph-explorer-api/pull/328/commits/461feccab249331e4dc2f6dda00f819fc57712d5) still produces the same [snippet diff](https://github.com/microsoftgraph/microsoft-graph-docs/commit/9ab1863a1b5947b58814b473c2c0e12c33b5aec2)

2020-10-05 21:02 UTC, zengin approved these changes

2020-10-05 21:02 UTC, zengin commented on CodeSnippetsReflection/LanguageGenerators/ObjectiveCGenerator.cs
> +                    if ((nameSpaceStringChunks.Length > 2) && nameSpaceStringChunks[0].Equals("microsoft") && nameSpaceStringChunks[1].Equals("graph"))
This can be assumed thanks to the namespace heuristic here: https://msazure.visualstudio.com/One/_wiki/wikis/Microsoft%20Graph%20Partners/54973/Type-namespaces?anchor=namespace-heuristic, but better to be defensive in the code ;)

For reference, corresponding logic in the generator is here: https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/blob/dev/src/GraphODataTemplateWriter/CodeHelpers/ObjC/TypeHelperObjC.cs#L143-L166

2020-10-06 07:30 UTC, merged

2020-10-06 07:34 UTC, andrueastman commented on CodeSnippetsReflection/LanguageGenerators/ObjectiveCGenerator.cs
> +                    if ((nameSpaceStringChunks.Length > 2) && nameSpaceStringChunks[0].Equals("microsoft") && nameSpaceStringChunks[1].Equals("graph"))
Thanks for this! 😄