- fixes a bug where non-flagabble enum properties would not be generated with proper type in java
microsoftgraph/microsoft-graph-explorer-api pull request #366
Opened 2020-11-04 17:51 UTC by baywet

2020-11-04 23:10 UTC, MIchaelMainer requested changes

2020-11-04 23:10 UTC, MIchaelMainer commented on CodeSnippetsReflection/LanguageGenerators/JavaGenerator.cs
> +                            stringBuilder.Append($"LinkedList<String> {currentListName} = new LinkedList<String>();\r\n");
I suggest that we either:
1) Make this an `elseif` that checks that this is an array of strings with a subsequent `else` that reports the identification that this as a new scenario that we need to support. For example, if we get an array of any OData primitive types that is not a string, we should identify the scenario and where we need to add the change. 
2) Add conditions for all OData primitive types.

I prefer the first for now.

Can we check that this is an array of strings?

2020-11-05 18:56 UTC, baywet commented on CodeSnippetsReflection/LanguageGenerators/JavaGenerator.cs
> +                            stringBuilder.Append($"LinkedList<String> {currentListName} = new LinkedList<String>();\r\n");
great minds connect! (did I properly translate the expression?) I was hunting for those kind of issues (wrong mapping of collections) and I was thinking about tackling the issue in a separate PR. But I included the fix here as well.

2020-11-05 21:40 UTC, zengin submitted a review, later dismissed

2020-11-06 22:17 UTC, zengin approved these changes

2020-11-06 22:36 UTC, nikithauc approved these changes

2020-11-07 04:11 UTC, MIchaelMainer approved these changes

2020-11-07 12:34 UTC, merged