Enable Sample Queries Testing
microsoftgraph/microsoft-graph-explorer-api pull request #381
Opened 2020-11-30 14:40 UTC by MaggieKimani1

This PR proposes addition of testing support for sample query files from DevX Content repo by workload teams using Graph Explorer.

2020-11-30 15:02 UTC, irvinesunday commented on GraphWebApi/Startup.cs
> +            //services.AddScoped<ISamplesTestStore, SamplesTestStore>();
Cleanup commented out code

2020-11-30 15:02 UTC, irvinesunday commented on GraphWebApi/Startup.cs
> +            services.AddScoped<IPermissionsTestStore, PermissionsTestStore>();
The interface and class implementation don't exist in the solution. You can remove this line.

2020-11-30 15:02 UTC, irvinesunday commented on GraphWebApi/Startup.cs
> +using GraphExplorerPermissionsService.Services;
This namespace is non-existence and not in use, you can remove this.

2020-11-30 15:05 UTC, irvinesunday commented
Why was the `GraphExplorerPermissionsController` class deleted?

2020-11-30 15:07 UTC, irvinesunday commented on GraphWebApi/Controllers/GraphExplorerSamplesController.cs
> +
Nitpick: Fix formatting - remove unnecessary whitespace between `if... else` block.

2020-11-30 15:10 UTC, irvinesunday commented on GraphWebApi/Startup.cs
> +            services.AddScoped<IPermissionsTestStore, PermissionsTestStore>();
Nitpick: Add `Scoped` services after or before `Singleton` services. Just for uniformity purposes 😉

2020-11-30 15:11 UTC, irvinesunday commented on GraphWebApi/Startup.cs
> +            services.AddHttpClient("github", c =>
Do we really need this service injected? Is it being used anywhere in the controllers?

2020-11-30 15:21 UTC, irvinesunday commented on GraphExplorerSamplesService/Services/SamplesTestStore.cs
> +            //order English translation of the sample queries
```suggestion
            // Order English translation of the sample queries
```

2020-11-30 15:23 UTC, irvinesunday commented on GraphExplorerSamplesService/Services/SamplesTestStore.cs
> +            if (!(responseMessage.IsSuccessStatusCode))
Nitpick: Remove unnecessary parentheses

2020-11-30 15:27 UTC, irvinesunday commented on GraphWebApi/Startup.cs
> +            services.AddHttpClient("github", c =>
I think we should abstract the logic of creating the `HttpClient` into a utility class within the FileService library. This is where the logic for reading all data sources live.

2020-11-30 15:30 UTC, irvinesunday commented on GraphExplorerSamplesService/Services/SamplesTestStore.cs
> +        private readonly string  _host;
```suggestion
        private readonly string _host;
```

2020-11-30 15:33 UTC, irvinesunday commented on GraphExplorerSamplesService/Services/SamplesTestStore.cs
> +            /* download sample query file contents*/
Nitpick: This comment feels redundant

2020-11-30 15:34 UTC, irvinesunday commented on GraphExplorerSamplesService/Services/SamplesTestStore.cs
> +        public SamplesTestStore(IHttpClientFactory httpClientFactory, IFileUtility fileUtility, IConfiguration configuration)
The `fileUtility` parameter is unused

2020-11-30 15:44 UTC, irvinesunday commented on FileService/Common/FileServiceHelper.cs
> +        public static string GetLocalizedFilePathSource(string containerName, string defaultBlobName, string localeCode = null, string source = null)
Parameter `source` is only used within this method as a flag to check whether the target is an Azure blob or GitHub blob. You may want to consider just using a boolean parameter instead.
Also update the XML documentation for any parameter added.

2020-11-30 16:54 UTC, MaggieKimani1 commented on FileService/Common/FileServiceHelper.cs
> +        public static string GetLocalizedFilePathSource(string containerName, string defaultBlobName, string localeCode = null, string source = null)
Oh yeah that's right, using a boolean parameter would suffice.

2020-11-30 17:00 UTC, irvinesunday commented on FileService/Common/FileServiceHelper.cs
> +                //This switch statement helps filter for only the supported locale languages
Nitpick: https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/inside-a-program/coding-conventions#commenting-conventions 😉

2020-11-30 17:03 UTC, irvinesunday commented on GraphExplorerPermissionsService/GraphExplorerPermissionsService.csproj
> +    <PackageReference Include="Microsoft.Extensions.Http" Version="2.2.0" />
Is this package used anywhere in the project?

2020-11-30 17:05 UTC, irvinesunday commented on GraphExplorerSamplesService/GraphExplorerSamplesService.csproj
> +    <PackageReference Include="Microsoft.Extensions.Http" Version="2.2.0" />
I don't think this is used anywhere in the project.

2020-11-30 18:59 UTC, ddyett commented on FileService/Services/BlobStorageUtility.cs
> +            if (!string.IsNullOrEmpty(host))
add a comment on what host being null means.

2020-11-30 19:01 UTC, ddyett commented on FileService/Interfaces/IFileUtility.cs
> +        Task<string> ReadFromFile(string filePathSource, string host = null);
document these methods so it's easier to understand what the parameters are meant to do.

2020-11-30 19:02 UTC, ddyett commented on GraphExplorerSamplesService/Interfaces/ISamplesTestStore.cs
> +    public interface ISamplesTestStore
document.

2020-11-30 19:54 UTC, ddyett commented on GraphWebApi/Startup.cs
> +            //services.AddScoped<ISamplesTestStore, SamplesTestStore>();
remove

2020-11-30 19:58 UTC, ddyett commented on GraphExplorerSamplesService/Services/SamplesTestStore.cs
> +    /// Defines a method that retrieves raw sample query files from the devX Content repo.
```suggestion
    /// Retrieves raw sample query files from the a GitHub repository.
```

2020-11-30 20:04 UTC, ddyett commented on GraphWebApi/Controllers/GraphExplorerSamplesController.cs
> +        public async Task<IActionResult> GetSampleQueriesListAsync(string search, string org, string branchName)
why does the user need to supply an org if the they can't supply the name of the repo.  It seems like org should also come from configuration and the user just supplies the branch name.

2020-11-30 20:07 UTC, ddyett commented on GraphExplorerSamplesService/Services/SamplesTestStore.cs
> +            bool orderSamples = locale.Equals("en-us", StringComparison.OrdinalIgnoreCase);
so the rest of the world gets treated slightly worse?  why?

2020-11-30 20:14 UTC, ddyett commented
no unit test cases. can we get some in.

2020-11-30 20:43 UTC, MaggieKimani1 commented on GraphWebApi/Controllers/GraphExplorerSamplesController.cs
> +        public async Task<IActionResult> GetSampleQueriesListAsync(string search, string org, string branchName)
This is for scenarios whereby a workload team member would like to test the files from a forked instance of the repo.
In this case, org will be replaced by their username so we'd still need to retain it as a query param.

2020-11-30 20:44 UTC, MaggieKimani1 commented on GraphExplorerSamplesService/Services/SamplesTestStore.cs
> +            bool orderSamples = locale.Equals("en-us", StringComparison.OrdinalIgnoreCase);
I think @irvinesunday would be the best person to answer this lol

2020-11-30 20:49 UTC, MaggieKimani1 commented on GraphExplorerPermissionsService/GraphExplorerPermissionsService.csproj
> +    <PackageReference Include="Microsoft.Extensions.Http" Version="2.2.0" />
Its going to be referenced when trying to create a HttpClientFactory instance to make calls to github using the permissions test store. Ideally, the file should have been excluded in the commit.

2020-11-30 22:23 UTC, irvinesunday commented on GraphExplorerSamplesService/Services/SamplesTestStore.cs
> +            bool orderSamples = locale.Equals("en-us", StringComparison.OrdinalIgnoreCase);
We still don't have a way of localizing Chinese or Japanese text alphabetically. There was an idea to add a new property `rank` with numerical values for all the sample categories. @bettirosengugi was pushing this. Not sure if it still is a priority.

2020-12-01 17:57 UTC, irvinesunday commented on FileService/Services/AzureBlobStorageUtility.cs
> +
Unnecessary diff.

2020-12-01 18:01 UTC, irvinesunday commented on FileService/Services/GithubBlobStorageUtility.cs
> +        public HttpClient _client { get; }
Should be `private`

2020-12-01 18:03 UTC, irvinesunday commented on FileService/Services/GithubBlobStorageUtility.cs
> +﻿using FileService.Interfaces;
Include license info.

2020-12-01 18:26 UTC, irvinesunday commented on GraphExplorerSamplesService/Services/SamplesStore.cs
> +        public SamplesStore(IConfiguration configuration, IMemoryCache samplesCache, GithubBlobStorageUtility githubBlobStorageUtility)
You don't really need a `GithubBlobStorageUtility` parameter in the constructor.

2020-12-01 18:27 UTC, irvinesunday commented on GraphExplorerSamplesService/Services/SamplesStore.cs
> +            _githubBlobFileUtility = githubBlobStorageUtility;
```suggestion
            _githubBlobFileUtility = new GithubBlobStorageUtility();
```

2020-12-01 18:33 UTC, irvinesunday commented on GraphExplorerSamplesService/Services/SamplesStore.cs
> +            string localizedFilePathSource = FileServiceHelper.GetLocalizedFilePathSource(_sampleQueriesContainerName, _sampleQueriesBlobName, locale);
This currently returns a file path with the structure: `containerName\\blobName` which is valid for Azure blob directories. What you want is a URI file path structure: `containerName/blobName` for GitHub Http requests

2020-12-01 18:34 UTC, irvinesunday commented on GraphExplorerSamplesService/Services/SamplesStore.cs
> +            var queriesFilePathSource = string.Concat(_host, org, _repo, branchName, FileServiceConstants.DirectorySeparator, localizedFilePathSource);
Same as above, the `FileServiceConstants.DirectorySeparator` returns a directory file path and ideally you want a URI file path.

2020-12-01 18:36 UTC, irvinesunday commented on GraphExplorerSamplesService/Services/SamplesStore.cs
> +        /// <param name="locale"></param>
Let's add descriptions to these param values.

2020-12-01 18:43 UTC, irvinesunday commented on GraphWebApi/appsettings.json
> +
Nit: Unnecessary whitespace

2020-12-01 18:45 UTC, irvinesunday commented on FileService/Services/GithubBlobStorageUtility.cs
> +        public GithubBlobStorageUtility(HttpClient client)
You don't really need a `HttpClient` parameter, you can just instantiate the `_client` field within the constructor.

2020-12-01 18:49 UTC, irvinesunday commented on FileService/Common/FileServiceConstants.cs
> +        public const string HostName = "github";
Is this used anywhere? If redundant you can remove.

2020-12-01 18:54 UTC, irvinesunday commented
Please fix failing tests.

2020-12-15 18:12 UTC, baywet commented
@MaggieKimani1 you might want to update the branch now to avoid having to do it later and resetting reviewers vote. :)

2020-12-15 22:19 UTC, irvinesunday approved these changes
👍🏽

2020-12-16 00:04 UTC, nikithauc commented on FileService/Services/HttpClientUtility.cs
> +        private readonly HttpClient _httpClient;
As per the following discussions -
HttpClient is intended to be instantiated once per application, rather than per-use.  
https://docs.microsoft.com/en-us/dotnet/api/system.net.http.httpclient?view=netframework-4.8
https://aspnetmonsters.com/2016/08/2016-08-27-httpclientwrong/ ? 
Can you please evaluate if making  HttpClient static or single instantiation will be useful here?

2020-12-16 00:05 UTC, nikithauc commented on FileService/Services/HttpClientUtility.cs
> +        public async Task<string> ReadFromFile(string filePathSource)
Please add summary to public methods and test cases added in this PR :)

2020-12-16 00:13 UTC, nikithauc commented on SamplesService.Test/SamplesStoreShould.cs
> +            Assert.Equal(149, espanolSampleQueriesList.SampleQueries.Count);
Please use constants -> const int currentSampleCount = 149 /151

2020-12-16 15:07 UTC, baywet requested changes

2020-12-16 15:07 UTC, baywet commented on FileService/Common/FileServiceConstants.cs
> +        public const int EspanolSampleCount = 149;
nit: would it be possible to move those counts to a configuration file?

2020-12-16 15:07 UTC, baywet commented on FileService/Services/HttpClientUtility.cs
> +            var httpResponseMessage = await _httpClient.GetAsync(filePathSource);
```suggestion
            using var httpResponseMessage = await _httpClient.GetAsync(filePathSource);
```

2020-12-16 15:07 UTC, baywet commented on GraphExplorerSamplesService/GraphExplorerSamplesService.csproj
> +    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="2.2.0" />
```suggestion
    <PackageReference Include="Microsoft.Extensions.Caching.Abstractions" Version="2.2.0" />
```

2020-12-16 15:07 UTC, baywet commented on GraphExplorerSamplesService/Services/SamplesStore.cs
>                      string jsonFileContents = _fileUtility.ReadFromFile(queriesFilePathSource).GetAwaiter().GetResult();
why not use an await since you already have an async here?

2020-12-16 15:07 UTC, baywet commented on GraphExplorerSamplesService/Services/SamplesStore.cs
> +            string jsonFileContents = _fileUtility.ReadFromFile(queriesFilePathSource).GetAwaiter().GetResult();
```suggestion
            string jsonFileContents = await _fileUtility.ReadFromFile(queriesFilePathSource);
```

2020-12-16 15:07 UTC, baywet commented on GraphWebApi/GraphWebApi.csproj
> +    <PackageReference Include="Microsoft.AspNetCore.App" />
```suggestion
    <PackageReference Include="Microsoft.AspNetCore.App" />
```

2020-12-16 15:07 UTC, baywet commented on GraphWebApi/appsettings.json
> +    "GithubHost": "https://raw.githubusercontent.com/",
should this setting be in the blod storage? or would it be better to move it to a different node?

2020-12-16 20:59 UTC, irvinesunday commented on GraphExplorerSamplesService/Services/SamplesStore.cs
>                      string jsonFileContents = _fileUtility.ReadFromFile(queriesFilePathSource).GetAwaiter().GetResult();
Cannot await in the body of a lock statement :)

2020-12-16 21:03 UTC, irvinesunday commented on FileService/Services/HttpClientUtility.cs
> +            var httpResponseMessage = await _httpClient.GetAsync(filePathSource);
Project is still using C# 7.3, might need upgrading to C# 8 for this syntax.

2020-12-17 13:07 UTC, baywet commented on GraphExplorerSamplesService/Services/SamplesStore.cs
>                      string jsonFileContents = _fileUtility.ReadFromFile(queriesFilePathSource).GetAwaiter().GetResult();
interesting, I haven't used locks in a while and I didn't know that

2021-01-07 13:04 UTC, baywet commented on FileService/Services/HttpClientUtility.cs
> +            var httpResponseMessage = await _httpClient.GetAsync(filePathSource);
I wasn't aware the project is still on 7.3, the response still needs to be disposed :)

2021-01-14 13:28 UTC, baywet approved these changes

2021-01-14 13:56 UTC, baywet requested changes

2021-01-14 13:56 UTC, baywet commented on MockTestUtility/FileUtilityMock.cs
>          public async Task WriteToFile(string fileContents, string filePathSource)
```suggestion
        public Task WriteToFile(string fileContents, string filePathSource)
```

The async without await is going to add a warning during build

2021-01-14 13:56 UTC, baywet commented on MockTestUtility/FileUtilityMock.cs
>              // Not implemented
```suggestion
            // Not implemented
            return Task.CompletedTask;
```

2021-01-25 13:41 UTC, baywet requested changes

2021-01-25 13:41 UTC, baywet commented on FileService/Interfaces/IHttpClientUtility.cs
> +        Task<string> ReadFromFile(HttpRequestMessage requestMessage);
nit: having the file notion in an http client sounds confusing. How about `ReadFromDocument` instead?

2021-01-25 13:41 UTC, baywet commented on FileService/Services/HttpClientUtility.cs
> +            var fileContents = await httpResponseMessage.Content.ReadAsStringAsync();
the null propagation at the previous line will give you null for the message if the client is null. 
Either add some defensive programming in the constructor or some null prop here as well.

2021-01-25 13:41 UTC, baywet commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +            var httpRequestMessage = new HttpRequestMessage(HttpMethod.Get, queriesFilePathSource);
```suggestion
            using var httpRequestMessage = new HttpRequestMessage(HttpMethod.Get, queriesFilePathSource);
```

2021-01-25 13:41 UTC, baywet commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +            var _applicationScopesInfoTable = new Dictionary<string, ScopeInformation>();
nit: move that after the null test for scopes, we don't need to initialize dictionaries if we're going to return null anyway

2021-01-25 13:41 UTC, baywet commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +            foreach (ScopeInformation delegatedScopeInfo in scopesInformationList.DelegatedScopesList)
```suggestion
           var _delegatedScopesInfoTable = new Dictionary<string, ScopeInformation>(scopesInformationList.DelegatedScopesList.Select(x => new KeyValuePair<string, ScopeInformation>(x.ScopeName, x));
```

This way you avoid:
- having to periodically grow the dictionary
- using a loop when the intend is to project data
- skipping on vectorialization

2021-01-25 13:41 UTC, baywet commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +                requestUrl = Regex.Replace(requestUrl, @"\?.*", string.Empty); // remove any query params
how often is this called? having the regexes as static fields would make them precompiled instead of compiling them every time here.

2021-01-25 13:41 UTC, baywet commented on GraphExplorerPermissionsService/Services/PermissionsStore.cs
> +                TemplateMatch resultMatch = _urlTemplateMatcher.Match(new Uri(requestUrl.ToLower(), UriKind.RelativeOrAbsolute));
```suggestion
                TemplateMatch resultMatch = _urlTemplateMatcher.Match(new Uri(requestUrl.ToLowerInvariant(), UriKind.RelativeOrAbsolute));
```

2021-01-25 13:41 UTC, baywet commented on GraphExplorerSamplesService/Services/SamplesStore.cs
> +            var httpRequestMessage = new HttpRequestMessage(HttpMethod.Get, queriesFilePathSource);
```suggestion
            using var httpRequestMessage = new HttpRequestMessage(HttpMethod.Get, queriesFilePathSource);
```

2021-01-25 13:41 UTC, baywet commented on GraphWebApi/Controllers/GraphExplorerPermissionsController.cs
>              _permissionsStore = permissionsStore;
nit: defensive programing

2021-01-25 13:41 UTC, baywet commented on GraphWebApi/Controllers/GraphExplorerSamplesController.cs
> +            _configuration = configuration;
nit: defensive programing

2021-01-28 17:35 UTC, baywet approved these changes

2021-01-28 17:35 UTC, baywet commented on FileService/Services/HttpClientUtility.cs
> +            if (requestMessage == null)
nit:
```suggestion
            requestMessage == null ?? throw new ArgumentNullException(nameof(requestMessage), "Value cannot be null.");
```

2021-01-28 17:36 UTC, baywet requested changes
actually sorry, I can see some of my previous comments haven't been taken into account/answered

2021-01-28 18:44 UTC, baywet commented on FileService/Services/HttpClientUtility.cs
> +            if (requestMessage == null)
ignore this one, sorry about the confusion

2021-01-28 18:50 UTC, baywet approved these changes

2021-01-28 18:52 UTC, merged